### PR TITLE
VA intake - Rollers of the Intake

### PR DESCRIPTION
**Pull request by AvianSilk**
An Intake subsystem was created

A command "TakeInTheBall" which takes in the ball

### CODE REVIEW

**Comment by jasonli0616** [comment]
Intake motor works, just a couple things before merging,

- Please put all your numbers in `Constants.java`! (eg. speed, motor ID, etc). This is so that we can make changes easily when needed (editing one file).
- Lower motor speed a bit, 1.0 is max speed which is too bit fast
- For your intake ball command, instead of using a 7 sec timer, try binding it to holding down a button instead

**Comment by jasonli0616** [comment]
Intake looks pretty good!

Consider having one method that will set left and right solenoids, instead of separate left and right commands? This is just to prevent having the solenoids physically in different states.
(also values in `Constants.java`!)

I see the intake ball command will activate the solenoids and spin the motor; let's test it out on Thursday!

**Comment by jasonli0616** [comment]
Also for Thursday when testing out the command:
Let's add a button binding to the command; instead of using a timer in the command, bind it to a [`button.whileHeld(cmd)`](https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/wpilibj/buttons/Button.html#whileHeld(edu.wpi.first.wpilibj.command.Command)).

**Comment by AvianSilk** [comment]
Thanks for the feedback !
I’ll (hopefully) work on your suggestions by Thursday

**Comment by jasonli0616** [comment]
Regarding activating solenoids:

See [constructor docs](https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/wpilibj/DoubleSolenoid.html#%3Cinit%3E(int,edu.wpi.first.wpilibj.PneumaticsModuleType,int,int))

One constructor takes in the pneumatics module ID, and one doesn't. Because our ID isn't the default one, use the constructor that takes in the ID (see link above).


Also, ensure your solenoids forward/reverse are in the right spot in the command!

**Comment by AvianSilk** [comment]
I made all the changes and pushed it

So it's basically ready to be merged unless I made a mistake

**Review by jasonli0616 — COMMENTED** [review]
Looks good!

The only thing to do before merging is to make sure that the intake motors are spinning the right way; so it takes in a ball instead of ejecting a ball, and vice versa.

Also another optional thing: consider using `intakeUp` and `intakeDown` instead of `intakeArmSet(state)`.

**Comment by jasonli0616** [comment]
Also maybe a eject ball command/button binding?

**Pull request merged**
